#!/usr/bin/env bash
# install nginx and configures port to listen on and querying return
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restartnew_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               sudo /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"

echo "$new_config" > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
