#!/usr/bin/env bash
# redirect of nginx to another page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sed -i '/^\tserver_name.*/a rewrite ^/redirect_me https://alx-intranet.hbtn.io// permanent;' /etc/nginx/sites-available/default
service nginx restart