#!/usr/bin/env bash
# redirect of nginx to another page
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s@#error_page 404 \/404.html;@location \/redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;}\n#error_page 404 \/404.html;@" /etc/nginx/sites-available/default
service nginx restart