#!/usr/bin/env bash
# redirect 404 page not found to custom message
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i "44i error_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart