#!/usr/bin/env bash
# install and configure HAproxy on server to serve as load balancer
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y update
sudo apt-get -y install haproxy=2.6.\*
echo -e '
frontend http-in
\tmode http
\tbind *:80
\tdefault_backend web_servers

backend web_servers
\tbalance roundrobin
\tserver 22108-web-01 3.236.140.13:80 check
\tserver 22108-web-02 3.238.133.193:80 check
' >> /etc/haproxy/haproxy.cfg
echo -e '
ENABLED=1' >> /etc/default/haproxy
sudo service haproxy restart
