#!/usr/bin/env bash
# Debugs error where sites-available/default is unlinked to site-enabled/default
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
