#!/usr/bin/env bash
#Nginx must be running, and listening on port 80
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo sed -i 's/8080/80/g' /etc/nginx/site-enabled/default
sudo service nginx restart
