#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo kill "$(pgrep 'nginx' | head -1)"
